x-app-environment: &app-environment
    APP_ENV: production
    APP_DEBUG: 'false'
    APP_URL: ${APP_URL}
    APP_KEY: ${APP_KEY}
    LOG_CHANNEL: stack
    DB_CONNECTION: pgsql
    DB_HOST: pgsql
    DB_PORT: 5432
    DB_DATABASE: ${DB_DATABASE}
    DB_USERNAME: ${DB_USERNAME}
    DB_PASSWORD: ${DB_PASSWORD}
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_PASSWORD: ${REDIS_PASSWORD}
    QUEUE_CONNECTION: redis
    SESSION_DRIVER: redis
    CACHE_STORE: redis
    BROADCAST_CONNECTION: log
    OSRM_BASE_URL: http://osrm:5000

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.prod
        image: planora-api-app:latest
        environment: *app-environment
        volumes:
            - app-code:/var/www/html
            - app-storage:/var/www/html/storage
        depends_on:
            pgsql:
                condition: service_healthy
            redis:
                condition: service_healthy
            osrm:
                condition: service_started
        networks:
            - app
        restart: unless-stopped

    web:
        image: nginx:stable-alpine
        depends_on:
            app:
                condition: service_started
        ports:
            - "${APP_HTTP_PORT:-80}:80"
        volumes:
            - app-code:/var/www/html:ro
            - app-storage:/var/www/html/storage
            - ./docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - app
        restart: unless-stopped

    queue:
        image: planora-api-app:latest
        command: php artisan queue:work --sleep=3 --tries=3 --backoff=10
        environment: *app-environment
        volumes:
            - app-code:/var/www/html
            - app-storage:/var/www/html/storage
        depends_on:
            pgsql:
                condition: service_healthy
            redis:
                condition: service_healthy
            osrm:
                condition: service_started
        networks:
            - app
        restart: unless-stopped

    scheduler:
        image: planora-api-app:latest
        command: php artisan schedule:work
        environment: *app-environment
        volumes:
            - app-code:/var/www/html
            - app-storage:/var/www/html/storage
        depends_on:
            pgsql:
                condition: service_healthy
            redis:
                condition: service_healthy
            osrm:
                condition: service_started
        networks:
            - app
        restart: unless-stopped

    pgsql:
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - pgsql-data:/var/lib/postgresql/data
        healthcheck:
            test:
                - CMD-SHELL
                - pg_isready -d "$${DB_DATABASE}" -U "$${DB_USERNAME}"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - app
        restart: unless-stopped

    redis:
        image: redis:7-alpine
        command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        volumes:
            - redis-data:/data
        healthcheck:
            test:
                - CMD-SHELL
                - redis-cli -a "$${REDIS_PASSWORD}" ping
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - app
        restart: unless-stopped

    osrm:
        image: osrm/osrm-backend
        platform: linux/amd64
        expose:
            - "5000"
        volumes:
            - osrm-data:/data
        healthcheck:
            test: ["CMD-SHELL", "curl -fsS 'http://localhost:5000/route/v1/driving/-74.0060,40.7128;-73.935242,40.73061?overview=false&steps=false' >/dev/null"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s
        command: >
            sh -c "DATA_FILE=/data/brooklyn.osm.pbf; OSRM_FILE=/data/brooklyn.osrm;
            if [ ! -f $DATA_FILE ]; then wget -O $DATA_FILE https://download.geofabrik.de/north-america/us/new-york-latest.osm.pbf; fi;
            if [ ! -f $OSRM_FILE ]; then osrm-extract -p /opt/car.lua $DATA_FILE && osrm-partition $OSRM_FILE && osrm-customize $OSRM_FILE; fi;
            osrm-routed --algorithm mld $OSRM_FILE"
        networks:
            - app
        restart: unless-stopped

networks:
    app:
        driver: bridge

volumes:
    app-code:
    app-storage:
    pgsql-data:
    redis-data:
    osrm-data:
